# Generated by Django 2.2.16 on 2020-11-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('social_networks', models.CharField(blank=True, max_length=300, verbose_name='Соц.сети')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
